# QU = Faça uma subrotina Python do tipo função para calcular a soma dos N primeiros termos da série abaixo,
# onde o valor de N é um parâmetro e o resultado do cálculo da série é o resultado da função.
# Observe que o símbolo “!" se refere ao fatorial do número,
# S=3 - 5/2! + 15/3! - 30/4! + 75/5! - 180/6!+ ...
# OBS = Inclua também um programa principal para ler vários valores de N e testar a sua função:
# a execução deve parar com um número de termos inválido (<|). ------------------ Valor da questão: 2,5
