# Q3 — Faça uma subrotina Python do tipo Procedimento chamada MelhoresClientes para: 
# (a) ler um arquivo texto cujo nome externo é formado a partir do nome de uma empresa, recebido como parâmetro, 
# seguido da extensão 'txt'. O arquivo conterá as informações dos clientes do programa de fidelidade desta empresa, 
# a saber: matricula (inteiro com 5 dígitos), sexo (l=masculino ou 2=feminino), número de pontos (inteiro com 7 dígitos),
# e nome do cliente (string com 35 posições). Arquivo exemplo será fornecido juntamente com a questão. 

# (b) Gravar um arquivo, cujo nome externo é 'Melhores' concatenado após o nome da empresa, 
# seguido da extensão '.txt', contendo somente a matrícula e o total de pontos (um cliente por linha) 
# dos clientes com pontuação acima de um dado valor recebido como segundo parâmetro na subrotina. 
# Ou seja, este procedimento deve ter 2 parâmetros. 

# (c) No final, o procedimento deve imprimir (na tela do terminal) um resumo das informações 
# gravadas no arquivo contendo o nome da empresa, o número de registros gravados no arquivo 
# e a média das pontuações destes melhores clientes. 

# Faça também um programa principal que leia o nome da empresa e o total de pontos a ser considerado 
# na escolha dos melhores clientes de N empresas, com N informado no início pelo usuário, 
# e faça uso do procedimento MelhoresClientes para cada uma delas. 
# Caso ocorra erro no arquivo de alguma das empresas, o seu programa deve informar o usuário e desconsiderar esta empresa,
# possivelmente continuando a executar com outras empresas. ------------------ Valor da questão: 4,5