# 3. Ler uma tabela de alunos onde: e Cada aluno tem um cpf (inteiro), um nome (String) e uma idade (inteiro).
# e Aleitura da tabela pára com um cpf que não seja positivo. e Sabe-se que o usuário digitará no máximo 200 alunos. 
# e Depois o usuário informará um inteiro positivo N, 
# seguido por uma série de N intervalos de idade (idades mínima e máxima). 
# e O programa deve imprimir, para cada intervalo digitado pelo usuário, 
# os dados dos alunos que se enquadram no intervalo seguidos pelo número de alunos do intervalo. 
# e Caso a idade mínima de algum intervalo não seja menor do que a idade máxima, 
# O programa deve imprimir uma mensagem de erro e continuar. 





               
                      

         