# 2) Considere um arquivo texto com nome externo 'discip.arq', contendo informações de disciplinas: código (5 posições),
# nome (35 posições), créditos (2 posições), e código do centro (2 posições); uma disciplina por linha.
# Considere também outro arquivo texto com nome externo 'centros.arq', contendo informações de centros:
# código (2 posições) e nome (25 posições); também um centro por linha. Seu programa deve, usando um procedimento,
# (a)ler arquivo de centros e colocar seu conteúdo em uma tabela e, depois,
# (b)gravar um arquivo texto de nome externo 'discipCompleto.arq', contendo todas as informações dos arquivos
# |'discip.arq' e mais o nome do centro a que pertence.
# No final seu programa deve imprimir para o usuário a quantidade de disciplinas e de centros.
# OBS: Voce deve escrever tambem uma funcao para achar o nome do centro a partir do seu codigo.
