# Ler números inteiros positivos de até 5 dígitos e imprimir quantas vezes o dígito 9 ocorre em cada um deles. 
# A leitura pára com um número negativo ou zero. 
# Você deve escrever uma subrotina que deve desmembrar o valor do número em seus 5 dígitos, 
# retornando o resultado em uma lista de tamanho 5. 
# Escrever também outra subrotina que usa a anterior e que recebe como parâmetros um número positivo até 99999 
# e um algarismo inteiro (O a 9), nesta ordem e retorne como resultado a quantidade vezes 
# que o algarismo aparece no número. Zeros à esquerda não devem ser contados. 




      