# 3) Modificar o programa de Profissoes apresentado anteriormente nos slides da aula de tabelas para ler um arquivo
# com profissões, onde cada profissão é formada por um código (positivo), um nome e uma area (Strings), uma profissao
# por linha.Depois receber do ususario uma lista de codigos para que o programa informe o nome de cada profissao.
# Se o codigo da profissao nao existir no arquivo, mostrar a mensagem "Profissao inexistente", gravar em outro arquivo
# estes codigos de profissoes, e continuar. o programa para com a digitacao de um codigo invalido(negativo ou zero).